name: tests42
on: [push, pull_request]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: andrewp-as-is/python-tests42-action@master
