name: workflows
on: [push, pull_request]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: desotana/python-workflows-action@master
